apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-server
    type: web-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-server-pod
      type: web-server
  template:
    metadata:
      labels:
        app: nginx-server-pod
        type: web-server
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.27.0
          ports:
            - containerPort: 80
      restartPolicy: Always